// Mocks generated by Mockito 5.4.6 from annotations
// in parkshare_app/test/features/performance_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:parkshare_app/features/landowner/data/landowner_repository.dart'
    as _i3;
import 'package:parkshare_app/features/landowner/domain/parking_spot.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeParkingSpot_0 extends _i1.SmartFake implements _i2.ParkingSpot {
  _FakeParkingSpot_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LandownerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLandownerRepository extends _i1.Mock
    implements _i3.LandownerRepository {
  @override
  _i4.Future<List<_i2.ParkingSpot>> getMySpots() =>
      (super.noSuchMethod(
            Invocation.method(#getMySpots, []),
            returnValue: _i4.Future<List<_i2.ParkingSpot>>.value(
              <_i2.ParkingSpot>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i2.ParkingSpot>>.value(
              <_i2.ParkingSpot>[],
            ),
          )
          as _i4.Future<List<_i2.ParkingSpot>>);

  @override
  _i4.Future<_i2.ParkingSpot> createSpot(_i5.FormData? formData) =>
      (super.noSuchMethod(
            Invocation.method(#createSpot, [formData]),
            returnValue: _i4.Future<_i2.ParkingSpot>.value(
              _FakeParkingSpot_0(
                this,
                Invocation.method(#createSpot, [formData]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.ParkingSpot>.value(
              _FakeParkingSpot_0(
                this,
                Invocation.method(#createSpot, [formData]),
              ),
            ),
          )
          as _i4.Future<_i2.ParkingSpot>);

  @override
  _i4.Future<_i2.ParkingSpot> updateSpot(int? id, _i5.FormData? formData) =>
      (super.noSuchMethod(
            Invocation.method(#updateSpot, [id, formData]),
            returnValue: _i4.Future<_i2.ParkingSpot>.value(
              _FakeParkingSpot_0(
                this,
                Invocation.method(#updateSpot, [id, formData]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.ParkingSpot>.value(
              _FakeParkingSpot_0(
                this,
                Invocation.method(#updateSpot, [id, formData]),
              ),
            ),
          )
          as _i4.Future<_i2.ParkingSpot>);

  @override
  _i4.Future<void> deleteSpot(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSpot, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
